departamentos = {
    'Amazonas': ['Leticia'],
    'Antioquia': ['Medellin'],
    'Arauca': ['Arauca'],
    'Atlantico': ['Barranquilla'],
    'Bolivar': ['Cartagena'],
    'Boyaca': ['Tunja'],
    'Caldas': ['Manizales'],
    'Casanare': ['Florencia'],
    'Cauca': ['Popayan'],
    'Cesar': ['Valledupar'],
    'Choco': ['Quibdo'],
    'Cundinamarca': ['Bogota'],
    'Guainia': ['Inirida'],
    'Guaviare': ['San Jose del Guaviare'],
    'Huila': ['Neiva'],
    'La Guajira': ['Riohacha'],
    'Magdalena': ['Santa Marta'],
    'Meta': ['Villavicencio'],
    'Nariño': ['Pasto'],
    'Norte de Santander': ['Cucuta'],
    'Putumayo': ['Mocoa'],
    'Quindio': ['Armenia'],
    'Risaralda': ['Pereira'],
    'San Andres y Providencia': ['San Andres'],
    'Santander': ['Bucaramanga', 'San gil', 'Piedecuesta', 'Barranca', 'Malaga', 'Giron'],
    'Sucre': ['Sincelejo'],
    'Tolima': ['Ibague'],
    'Valle del Cauca': ['Cali'],
    'Vaupes': ['Mitu'],
    'Vichada': ['Puerto Carreño']
}
